### ISSUE TITLE
How to find resources connected to another computer (not localhost)?

### ISSUE THREAD

**Issue by zfthink** [pfroud/JVisa#11]
At present, I use `resourceManager.openInstrument("TCPIP0::192.168.1.11::1799::SOCKET");` to implement. In fact, I want to get resources from another IP first.

I am using Centos7.X and NI-VISA.

Can you add a constructor like `resourceManager.findResources("xxx.xxx.xxx.xxx");` to implement it?

**Comment by pfroud** [comment]
I don't think I understand your question.

When you open an instrument at `"TCPIP0::192.168.1.11::1799::SOCKET"`, is that the IP address or the other computer, or the IP address of the resource you want to open?

I think you need to use NI-VISA Server:

* [How Do I Control My VISA Device from Another Computer?](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q000000YIFCCA4)
* [How to Configure and Use Remote NI-VISA](https://www.ni.com/docs/en-US/bundle/ni-visa/page/ni-visa/howtoconfigureuseremoteni-visa.html)

**Comment by zfthink** [comment]
Here's the scenario：

The server that i use to run JVISA and the device machine are in a local area network , and they two have different IP（for eg : IP of the server is 192.168.1.10 and IP of the device machine is 192.168.1.11）.

At the present ,  I can not use **resourceManager.findResources()**  to find resources from the device machine , I can only use **resourceManager.openInstrument("TCPIP0::192.168.1.11::1799::SOCKET")** to connect the device resource . 

In fact , I want to find resources from the device machine firstly  ,then use **resourceManager.openInstrument(resourceName)** to connect it.

**Comment by pfroud** [comment]
Can you clarify what you mean by "device machine"?

**Comment by zfthink** [comment]
A deivce who have VISA resources

**Comment by pfroud** [comment]
First, follow these instructions to set up the VISA server:

* [How Do I Control My VISA Device from Another Computer?](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q000000YIFCCA4)
* [How to Configure and Use Remote NI-VISA](https://www.ni.com/docs/en-US/bundle/ni-visa/page/ni-visa/howtoconfigureuseremoteni-visa.html)

Then call:

```java
resourceManager.findResources("visa://remoteHosenameOrIPAddress/?*");
```

See documentation for [viFindRsrc](https://www.ni.com/docs/en-US/bundle/ni-visa/page/ni-visa/vifindrsrc.html)

**Comment by zfthink** [comment]
copy,thank you 


---- Replied Message ----
| From | Peter ***@***.***> |
| Date | 2/27/2023 14:30 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [pfroud/JVisa] How to find resources connected to another computer (not localhost)? (Issue #11) |

First, follow these instructions to set up the VISA server:

How Do I Control My VISA Device from Another Computer?
How to Configure and Use Remote NI-VISA

Then call:

resourceManager.findResources("visa://remoteHosenameOrIPAddress/?*");

See documentation for viFindRsrc
