### ISSUE TITLE
Does JVisa support communication with ASRL?::INSTR?

### ISSUE THREAD

**Issue by changhexuefei** [pfroud/JVisa#12]
Hello, does the JVisa library support the communication of converting the serial port address to ASRL?::INSTR?

![image](https://github.com/pfroud/JVisa/assets/19502034/f819f62f-af4a-4453-98d6-f626a206376e)

**Comment by pfroud** [comment]
Hi, JVisa does support communication with ASRL#::INSTR resources.

Here are two things that might help:

* You can read the alias. By default, the alias is "COM#", but it can be changed in NI-MAX.

* You can read the [`VI_ATTR_INTF_NUM`](https://www.ni.com/docs/en-US/bundle/ni-visa/page/ni-visa/vi_attr_intf_num.html) attribute according to this article: [Determining VISA COM Port Binding](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q000000YIfPCAW&l=en-US)).

Example code:

```java
import xyz.froud.jvisa.JVisaException;
import xyz.froud.jvisa.JVisaInstrument;
import xyz.froud.jvisa.JVisaLibrary;
import xyz.froud.jvisa.JVisaResourceManager;
public class SerialPortExample {
    public static void main(String[] args) throws JVisaException {
        try (JVisaResourceManager resourceManager = new JVisaResourceManager()) {
            final String[] resourceNames = resourceManager.findResources();
            for (String resourceName : resourceNames) {
                final String alias = resourceManager.getInstrumentAlias(resourceName);
                final JVisaInstrument instrument = resourceManager.openInstrument(resourceName);
                final byte interfaceNumber = instrument.getAttributeBytes(JVisaLibrary.VI_ATTR_INTF_NUM, 1)[0];
                System.out.printf("resourceName = \"%s\", alias = \"%s\", INTF_NUM = %d\n",
                        resourceName, alias, interfaceNumber);
            }
        }
    }
}

```

Sample output with the default aliases:

```
resourceName = "ASRL3::INSTR", alias = "COM3", INTF_NUM = 3
resourceName = "ASRL4::INSTR", alias = "COM4", INTF_NUM = 4
```

Sample output after I changed the aliases using NI-MAX:

```
resourceName = "ASRL3::INSTR", alias = "qwertyuiop", INTF_NUM = 3
resourceName = "ASRL4::INSTR", alias = "asdfghjkl", INTF_NUM = 4
```

**Comment by changhexuefei** [comment]
Hello, the example code you gave cannot run successfully on my side, and the instrument does not have a getAttributeBytes method. Why?



![image](https://github.com/pfroud/JVisa/assets/19502034/2bd19493-7a6d-43b0-9a24-5f01328ec71e)

**Comment by changhexuefei** [comment]
This is my previous code, running it shows a timeout error


![image](https://github.com/pfroud/JVisa/assets/19502034/31c16659-9bb8-4f7f-971e-8f139eb467c9)

**Comment by pfroud** [comment]
Oops, the `getAttributeBytes()` method is not in JVisa release 1.0.

Probably you need to set the serial port baud rate. First, test communication using NI-MAX. 

Click this button
![image](https://github.com/pfroud/JVisa/assets/9056906/f39af4ba-317b-4ad5-95b2-496b11ee48ce)

then change settings 

![image](https://github.com/pfroud/JVisa/assets/9056906/41063a8f-996b-44a5-8db7-02d10497de8a)

Then click on the second tab, then you can send the `*IDN?` query

![image](https://github.com/pfroud/JVisa/assets/9056906/6d6ce90f-8c8d-40ff-ae86-6bd7b7b52fc2)

Tell me if it works.

**Comment by changhexuefei** [comment]
This is the setup in NI MAX and it works fine

![image](https://github.com/pfroud/JVisa/assets/19502034/9db22bc6-6f5a-4dde-b9bc-9861fdac5eab)
![image](https://github.com/pfroud/JVisa/assets/19502034/e74fe905-6bf4-429e-94f9-9923df020f00)

**Comment by pfroud** [comment]
I added methods to set the serial port parameters.

Please get the newest JVisa code from Github (`git clone` or download zip from website) then try this:
```java
instrument.setSerialBaudRate(9600);
instrument.setSerialDataBits(8);
instrument.setSerialStopBits(SerialStopBits.ONE);
instrument.setSerialParity(SerialParity.NONE);
```

I renamed the `sendAndReceiveString` method to `queryString`, so you call
```java
System.out.println(instrument.queryString("*IDN?"));
```

The NI-VISA documentation says the default values match the values in your NI-MAX screenshot. If it still does not work, pls send screenshots of the "Flow Control Settings" tab and the "I/O Settings" tab.

![image](https://github.com/pfroud/JVisa/assets/9056906/1fd75c00-1ce7-4315-a583-6417cc00e855)

**Comment by changhexuefei** [comment]
I used your new file, but it still has a timeout error.

![image](https://github.com/pfroud/JVisa/assets/19502034/4eb7868b-16fc-4f64-ad68-41fb9b97ebbe)
![image](https://github.com/pfroud/JVisa/assets/19502034/a67c2e25-54f8-492c-8cba-41a09831c59e)
![image](https://github.com/pfroud/JVisa/assets/19502034/bc2b14eb-ccd6-4d0b-b446-8b903378df32)

**Comment by pfroud** [comment]
I don't know why it isn't working.

If you want to continue debugging, can you try using [PyVISA](https://pyvisa.readthedocs.io/)? Both PyVISA and JVisa are wrappers around the NI-VISA DLL. It will help us isolate the problem.

Here's how you set the serial parameters: https://github.com/pyvisa/pyvisa/issues/326#issuecomment-379070957

**Comment by changhexuefei** [comment]
Hello, I used both Java and python to write the code to communicate with the device. I use pyvisa to communicate with the device in python, and there is no such problem.

![image](https://github.com/pfroud/JVisa/assets/19502034/7c9b7cfb-0e60-481e-be69-217a5ec579a3)
![image](https://github.com/pfroud/JVisa/assets/19502034/5556f638-c585-4967-a8b6-e4e3fbff8eda)


The following is the information of pyvisa
![image](https://github.com/pfroud/JVisa/assets/19502034/e5a8007c-e3c0-42d6-b6d8-ed80de22a20a)

**Comment by changhexuefei** [comment]
The following visa library is used for pyvisa communication in python3.10:

![image](https://github.com/pfroud/JVisa/assets/19502034/463ef309-2155-4389-b313-171be24f829e)

**Comment by changhexuefei** [comment]
Hello, when I set the termination character for reading and writing, I can communicate normally now, thank you for your support.

![image](https://github.com/pfroud/JVisa/assets/19502034/929f15f6-e583-4a33-8fba-ba9654807882)

**Comment by changhexuefei** [comment]
![image](https://github.com/pfroud/JVisa/assets/19502034/991fbae0-ae64-4554-a637-56479e3acc96)
