### ISSUE TITLE
Does JVisa support requesting and parsing binary block data?

### ISSUE THREAD

**Issue by changhexuefei** [pfroud/JVisa#13]
PyVisa uses query_binary_values method to parse blocks of binary data，does JVisa support parsing binary block data?

**Comment by pfroud** [comment]
Right now JVisa does not have a method to parse a binary block. I think it is easy, I will add it.

Documentation in this discussion:  https://github.com/pfroud/JVisa/discussions/10#discussioncomment-5059595

Links to PyVisa functions:
* [`query_binary_values`](https://github.com/pyvisa/pyvisa/blob/e01a7093b1df28f907631d96ba8699a8f0287023/pyvisa/resources/messagebased.py#L691)
* [`read_binary_values`](
https://github.com/pyvisa/pyvisa/blob/e01a7093b1df28f907631d96ba8699a8f0287023/pyvisa/resources/messagebased.py#L533)
* [`parse_ieee_block_header`](https://github.com/pyvisa/pyvisa/blob/e01a7093b1df28f907631d96ba8699a8f0287023/pyvisa/util.py#L371)
* [`parse_hp_block_header`](https://github.com/pyvisa/pyvisa/blob/e01a7093b1df28f907631d96ba8699a8f0287023/pyvisa/util.py#L448)

**Comment by changhexuefei** [comment]
We look forward to your upgrade of the JVisa library

**Comment by pfroud** [comment]
Please post a sample of the data you want to parse. You can use the VISA Test Panel in NI-MAX. I only need to see the beginning of the bytes. 

For example, a screenshot from `dist:data?` on a Rigol oscilloscope returns
```
#9001152054BM6\94\11\00\00\00\00\006\00\00\00(\00\00\00\s\03\00...
```

**Comment by changhexuefei** [comment]
The following is the data
1: Write Operation (:WAVeform:DATA?)

Return Count: 15 bytes

2: Read Operation
Return Count: 1024 bytes
#800488251\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\80\
80\80\80\80\80\80\80\80\80\80\80

**Comment by pfroud** [comment]
I added code on branch [add-data-block](https://github.com/pfroud/JVisa/tree/add-data-block). I can take a screenshot from my instrument:

```java
byte[] bytes = instrument.queryBinaryBlock("display:data?");
Files.write(Paths.get("screenshot.bmp"), bytes);
```

Check the programming manual for your instrument about `waveform:data?`. For the [Rigol DS1000Z series oscilloscope](https://beyondmeasure.rigoltech.com/acton/attachment/1579/f-0386/1/-/-/-/-/DS1000Z_Programming%20Guide_EN.pdf), it says

> Before reading the waveform data in the internal memory, you need to judge whether the waveform data can all be read at one time according to the memory depth of the oscilloscope and the maximum number of waveform points that can be read each time.

**Comment by changhexuefei** [comment]
When using the new method, such an error was reported, "in viRead(): VI_SUCCESS_MAX_CNT: The number of bytes read is equal to count (0x3FFF0006)"

**Comment by changhexuefei** [comment]
Below is the programming documentation for the instrument I am using.


[4000X-Programming.pdf](https://github.com/pfroud/JVisa/files/12036949/4000X-Programming.pdf)

**Comment by changhexuefei** [comment]
When this problem occurs, pyvisa handles it as follows:


![image](https://github.com/pfroud/JVisa/assets/19502034/23256f5e-580d-4c51-ae8c-f881435ae30f)

**Comment by pfroud** [comment]
The `VI_SUCCESS_MAX_CNT` status should be handled, see 

https://github.com/pfroud/JVisa/blob/f1aa131e3b07d2f3a4be4fa2397b9ef5a3a1022b/src/main/java/xyz/froud/jvisa/JVisaResourceManager.java#L315

and

https://github.com/pfroud/JVisa/blob/f1aa131e3b07d2f3a4be4fa2397b9ef5a3a1022b/src/main/java/xyz/froud/jvisa/JVisaResourceManager.java#L350

**Comment by changhexuefei** [comment]
Sorry, I just copied part of the code, now after copying all the code, it can work, thank you

**Comment by changhexuefei** [comment]
The following is the return value obtained by sending the "waveform data?" command using PyVisa and JVisa, and why they are different. The first picture is the result of pyvisa, and the second picture is the result of JVisa.
![image](https://github.com/pfroud/JVisa/assets/19502034/99b65739-64af-4182-b9df-a559a5763e7c)



![image](https://github.com/pfroud/JVisa/assets/19502034/a9456922-9fc4-4e37-a1c5-968d4ecc936e)

**Comment by pfroud** [comment]
I think it is different signed vs unsigned interpretation of `byte` primitive. Try this 

```java
for (int i = 0; i < bytes.length; i++) {
    System.out.println(i + " = " + Byte.toUnsignedInt(bytes[i]));
}
```

**Comment by changhexuefei** [comment]
yes,thank you ,I get it

**Comment by pfroud** [comment]
Hi, if the `queryBinaryBlock()` method works, can we close this issue?

**Comment by changhexuefei** [comment]
Yes, we can close this issue.

**Comment by changhexuefei** [comment]
Is it considered to publish the newly added part as an official version?

**Comment by pfroud** [comment]
Yes, I plan to make an official release with the newly added features

**Comment by pfroud** [comment]
Released in [2.0.0](https://github.com/pfroud/JVisa/releases/tag/2.0.0)
