### ISSUE TITLE
JVisa whether you can read and write 16-base data?

### ISSUE THREAD

**Issue by Rx-out** [pfroud/JVisa#14]
JVisa whether you can read and write 16-base data?
can you give an example?

**Comment by pfroud** [comment]
Please give an example of what you want to do

**Comment by Rx-out** [comment]
![1710313464977](https://github.com/pfroud/JVisa/assets/41980447/aec716d5-b29a-4c99-b4b0-2fd9133b254c)

send hexadecimal data  device

**Comment by pfroud** [comment]
The string `"01 03 00 80 00 07"` contains the character `0`, then the character `1`, then a space character, and so on.

Demonstration: 

```java
public static void main(String[] args) {
    printStringBytesInHex("ABCD");
    printStringBytesInHex("01 03 00 80 00 07");
}

private static void printStringBytesInHex(String str) {
    final byte[] bytes = str.getBytes(java.nio.charset.StandardCharsets.US_ASCII);
    for (int i = 0; i < bytes.length; i++) {
        System.out.printf("%02X ", bytes[i]);
    }
    System.out.println();
}
````

Sample output:

```
41 42 43 44 
30 31 20 30 33 20 30 30 20 38 30 20 30 30 20 30 37 
```

Table of ASCII characters:

![ASCII table](https://upload.wikimedia.org/wikipedia/commons/b/b3/ASCII-Table.png)

I will add JVisaInstrument methods to send bytes instead of a string.

**Comment by Rx-out** [comment]
It's not what I wanted, thank you! I don't speak English very well and didn't describe the problem clearly! Thank you very much for your reply ,It's a pleasure to communicate with you, can you leave a contact information?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peter ***@***.***&gt;; 
发送时间: 2024年3月14日(星期四) 上午7:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pfroud/JVisa] JVisa whether you can read and write 16-base data? (Issue #14)





 
The string "01 03 00 80 00 07" contains the character 0, then the character 1, then a space character, and so on.
 
Demonstration:
 public static void main(String[] args) {     printStringBytesInHex("ABCD");     printStringBytesInHex("01 03 00 80 00 07"); } private static void printStringBytesInHex(String str) {     final byte[] bytes = str.getBytes(java.nio.charset.StandardCharsets.US_ASCII);     for (int i = 0; i < bytes.length; i++) {         System.out.printf("%02X ", bytes[i]);     }     System.out.println(); }
 
Sample output:
 41 42 43 44  30 31 20 30 33 20 30 30 20 38 30 20 30 30 20 30 37   
Table of ASCII characters:
 

 
I will add JVisaInstrument methods to send bytes instead of a string.

**Comment by pfroud** [comment]
You are welcome!

I added methods to write `byte[]` instead of `String`, please test it:

https://github.com/pfroud/JVisa/blob/7d018d4218004dd44b5128cc1340bc135475c7c7/src/main/java/xyz/froud/jvisa/JVisaInstrument.java#L207

Let me know if you need help getting the new code.

**Comment by pfroud** [comment]
Can you test the new method to write a `byte[]`?
