### ISSUE TITLE
JVisa for Android  

### ISSUE THREAD

**Issue by ccorrea97** [pfroud/JVisa#15]
Hi, how are you?

I need to develop an Android app capable of communicate with an oscilloscope which support SCPI commands (I have it currently working in a Windows environment with Py VISA). 

I see the supported OSs in the description, but I wonder if this library would work in an Android OS. In case it doesn't, or it is uncertain, would you help me giving me a hint of what kind of solution would be a better approach? If mixing Java with C (which I understand work well with VISA) or better go with C# (having .NET working with NI-VISA) and Xamarin (for Android, because C# is not officially supported by Android, when Java and/or Kotlin yes).

(If you need context and my question is not out of place in the first place, I'm aiming to develop an app for Android which retrieves data from an Owon VDS6102 oscilloscope and show it in charts and graphs.)

Thank you in advance.

**Comment by pfroud** [comment]
I don't think JVisa can work on Android. JVisa does not actually do VISA itself, it is only a wrapper around a VISA implementation.

I know of four VISA implementations. Some of them support Linux, but none say they support Android:

* Keysight IO Libraries Suite: [CentOS, Red Hat, Ubuntu](https://www.keysight.com/us/en/lib/software-detail/computer-software/io-libraries-suite-downloads-2175637.html)
* NI-VISA: [RedHat, SUSE, Ubuntu](https://www.ni.com/en/support/downloads/drivers/download.ni-visa.html#523634)
* Tektronix TekVISA: [Windows only](https://www.tek.com/en/support/faqs/how-can-i-communicate-tektronix-instrument-unix-or-linux)
* Rohde & Schwarz RSVISA : [Raspbian, CentOS, openSUSE, Ubuntu](https://www.rohde-schwarz.com/us/applications/r-s-visa-application-note_56280-148812.html)


I see your oscilloscope has USB and Ethernet. USB is difficult to reverse-engineer but network might be easier. The oscilloscope hopefully uses [LXI](https://www.lxistandard.org/Specifications/Specifications.aspx). You can try connecting the oscilloscope to your PC over the network, using the oscilloscope software to control it, and look at the network traffic using a packet sniffer / protocol analyzer software.

[Wireshark](https://www.wireshark.org/) is standard but it can't tell which Windows process sent network traffic. I also suggest trying [Microsoft Network Monitor](https://www.microsoft.com/en-us/download/details.aspx?id=4865) (archived, no longer under development, still works).

If you can find what network packets are used to discover and control the instrument, you can probably send the same packets from Android.
