### ISSUE TITLE
How to Determine the Actual Length of CALC:DATA? SDATA for Full Data Read

### ISSUE THREAD

**Issue by yuyangyumi** [pfroud/JVisa#17]
I am encountering an issue while trying to read data, as follows:

I need to read the complete data from CALC:DATA? SDATA.
The current problem is that I do not know the actual length of SDATA, which prevents me from determining how much data to read.

I would like to know if there is a method to retrieve the actual length of SDATA or if there is another way to ensure that I can read the complete SDATA data.

I don’t understand these. Could you please help me solve this issue? Thank you very much.
https://www.rohde-schwarz.com/webhelp/ZNB_ZNBT_HTML_UserManual_en/Content/a4bd89b090df4be7.htm

**Comment by pfroud** [comment]
It seems there is no way to know the actual response length before reading the response. Here are other discussions about it: [1](https://forums.ni.com/t5/LabWindows-CVI/CVI2015-viRead-and-buffer-size/td-p/3816124), [2](https://lavag.org/topic/8809-how-to-use-visa-read-in-a-neat-way/), [3](https://forums.ni.com/t5/LabWindows-CVI/How-to-know-the-buffer-size-before-viRead/td-p/4215137)

Here is what I found for your instrument:

You can change the format returned by `CALC:DATA?` by first sending [`FORMat[:DATA] <TransferFormat>`](https://www.rohde-schwarz.com/webhelp/ZNB_ZNBT_HTML_UserManual_en/Content/fd9584184d114c87.htm#d2539297e134318).

* If `<TransferFormat>` is set to `ASCII`, then the response to `CALC:DATA?` has unknown length. I wrote about what to do about that below.
* If `<TransferFormat>` is set to `REAL`, then the response to `CALC:DATA?` starts with a header which tells you the length. You can use JVisa methods [`JVisaInstrument.readBinaryBlock()`](https://github.com/pfroud/JVisa/blob/060b4725b796824b1e6df945860e0f0ef80c0dbd/src/main/java/xyz/froud/jvisa/JVisaInstrument.java#L298) or `queryBinaryBlock()`. The R&S documentation calls the format "definite length block", I have also seen it called "definite-length arbitrary block" or "definite-length data block".

&nbsp;

**How to read response of unknown length??**

I think the strategies are:

* Request a very large number of bytes, for example `myInstrument.readBytes(99999)`. Nothing bad will happen if you try to read more bytes than are available. You  might need to increase the timeout by calling [JVisaInstrument.setTimeout()](https://github.com/pfroud/JVisa/blob/02435397adcc067982860371b1868b065ca03670/src/main/java/xyz/froud/jvisa/JVisaInstrument.java#L388).
* Repeatedly call `JVisaInstrument.readBytes()`. For example if the instrument sent 300 bytes and you call `myInstrument.readBytes(100)`, you can then call `readBytes(200)`.

There is also the [termination character](https://www.ni.com/en/support/documentation/supplemental/06/termination-characters-in-ni-visa.html). The methods in `JVisaInstrument` are `setReadTerminationCharacter(char)` and `setReadTerminationCharacterEnabled(boolean)`.

We can use [PyVISA](https://github.com/pyvisa/pyvisa) as a reference implementation:

* The [`read_bytes()`](https://github.com/pyvisa/pyvisa/blob/4cf9232bfe24546508b96dc82d44176dd2fed494/pyvisa/resources/messagebased.py#L384-L400) function repeatedly calls `read()` until the length of the accumulated bytes reaches the total number of requested bytes.

* The [`_read_raw()`](https://github.com/pyvisa/pyvisa/blob/4cf9232bfe24546508b96dc82d44176dd2fed494/pyvisa/resources/messagebased.py#L466-L476) function repeatedly calls `read()` until the status code is [`VI_SUCCESS_MAX_CNT`](https://www.ni.com/docs/en-US/bundle/ni-visa-api-ref/page/ni-visa-api-ref/completion_codes.html) which means "the number of bytes read is equal to the input count".

**Comment by yuyangyumi** [comment]
Thank you for your response, it is incredibly helpful to me, thank you very much. I can now access the complete data, but I am facing a new problem. After obtaining this string of binary data, I am unsure how to parse it. I am not certain whether the parsing code I wrote is for the R&S ZNB8. If possible, could you please take a look? I would greatly appreciate your guidance.

Here is my SCPI code.
```
*RST
SYST:ERR:ALL?
SENS:FREQ:STAR 100
SENS:FREQ:STOP 1e8
CALC:PAR:DEF:EXT 'S21', S21
INIT:IMM; *WAI
FORM REAL, 32
CALC:DATA? SDATA
```

Below is the attachment for my output data.

[test.zip](https://github.com/user-attachments/files/17456665/test.zip)

Here is my parsing code.
```java
/**
 * Convert response data to Touchstone format and save to a file.
 *
 * @param response       The byte array containing the data.
 * @param startFrequency The start frequency in Hz.
 * @param endFrequency   The end frequency in Hz.
 * @param outputFile     The path to the output Touchstone file.
 */
public static void convertToTouchstone(byte[] response, double startFrequency, double endFrequency, String outputFile) {
    StringBuilder touchstoneBuilder = new StringBuilder();
    touchstoneBuilder.append("# Hz S RI R 50\n"); // Add Touchstone file header information

    // Parse response data
    int numPoints = response.length / 8; // Each data point contains two 32-bit floats (real and imaginary parts)
    for (int i = 0; i < numPoints; i++) {
        float real = ByteBuffer.wrap(response, i * 8, 4).order(ByteOrder.LITTLE_ENDIAN).getFloat();
        float imag = ByteBuffer.wrap(response, i * 8 + 4, 4).order(ByteOrder.LITTLE_ENDIAN).getFloat();
        double frequency = startFrequency + i * (endFrequency - startFrequency) / numPoints;
        touchstoneBuilder.append(String.format("%f %f %f\n", frequency, real, imag));
    }

    // Write Touchstone format data to file
    try (FileWriter writer = new FileWriter(outputFile)) {
        writer.write(touchstoneBuilder.toString());
        System.out.println("Touchstone file written to " + outputFile);
    } catch (IOException e) {
        System.err.println("Failed to write Touchstone file: " + e.getMessage());
    }
}

/**
 * Convert response data to CSV format and save to a file.
 *
 * @param response       The byte array containing the data.
 * @param startFrequency The start frequency in Hz.
 * @param endFrequency   The end frequency in Hz.
 * @param outputFile     The path to the output CSV file.
 */
public static void convertToCSV(byte[] response, double startFrequency, double endFrequency, String outputFile) {
    StringBuilder csvBuilder = new StringBuilder();
    csvBuilder.append("Frequency (Hz), Real, Imaginary\n"); // Add CSV file header information

    // Parse response data
    int numPoints = response.length / 8; // Each data point contains two 32-bit floats (real and imaginary parts)
    for (int i = 0; i < numPoints; i++) {
        float real = ByteBuffer.wrap(response, i * 8, 4).order(ByteOrder.LITTLE_ENDIAN).getFloat();
        float imag = ByteBuffer.wrap(response, i * 8 + 4, 4).order(ByteOrder.LITTLE_ENDIAN).getFloat();
        double frequency = startFrequency + i * (endFrequency - startFrequency) / numPoints;
        csvBuilder.append(String.format("%f,%f,%f\n", frequency, real, imag));
    }

    // Write CSV format data to file
    try (FileWriter writer = new FileWriter(outputFile)) {
        writer.write(csvBuilder.toString());
        System.out.println("CSV file written to " + outputFile);
    } catch (IOException e) {
        System.err.println("Failed to write CSV file: " + e.getMessage());
    }
}
```

**Comment by changhexuefei** [comment]
I see that you are reading the S parameter data from the network, and you should get binary block data. There is a queryBinaryBlock() method in JVisa. I wonder if it can meet your needs?

**Comment by yuyangyumi** [comment]
The program has now terminated correctly, and queryBinaryBlock has received a data response. However, I am unsure whether the data is truly complete and how it should be parsed.

I’m not sure if my handling is correct, and if it’s not, what should I do?

**Comment by yuyangyumi** [comment]
I’m sorry, but due to uncertainty regarding whether the data is accurate, I’m currently unable to determine if this method meets my needs, so I cannot answer your question. I need to verify that the data matches the data being returned before I can proceed.

**Comment by yuyangyumi** [comment]
However, the data in the current attachment, test.zip, comes from the return of queryBinaryBlock, which is good news. But I’m not sure if the data is correct. Currently, the method I wrote can convert to touchstone and csv, but I’m not certain that my method of converting the data is accurate.

**Comment by changhexuefei** [comment]
My job is also to get data from measurement equipment, but we use Keysight's network analyzer, which contains binary block data. Can you send the data?

**Comment by changhexuefei** [comment]
You can run the network analyzer, save it as an SNP file, and then compare it with your converted data.

**Comment by yuyangyumi** [comment]
Yes, I am trying to do this, but my previous job was a web frontend engineer. I lack a lot of experience in the fields of CNC (Computer Numerical Control) and measurement analysis.

**Comment by yuyangyumi** [comment]
Therefore, I need professionals who understand this area to help me confirm whether this code is correct. If it is correct, it will give me more confidence.

**Comment by pfroud** [comment]
To check how to parse the response from `CALC:DATA? SDATA`, try setting the `FORMAT` to `ASCII`.

Although we don't know the response length, if you make the buffer size extremely large (for example` myInstrument.readString(99999)`) it should work.

You might need to increase the timeout by calling `myInstrument.setTimeout()` before calling `readString()`.

If you post the `ASCII` and `REAL` output for the same analyzer inputs and settings, we can find how to parse the binary.

**Comment by yuyangyumi** [comment]
Thank you very much, with your help, I successfully verified the data, parsed the data format, and obtained the correct results and image display.
