### ISSUE TITLE
Does this library work on Linux?

### ISSUE THREAD

**Issue by Jsing** [pfroud/JVisa#2]
Hello,

Thank you for your efforts in sharing this library. I am trying to use visa on linux. Have you ever tested whether this library works well on Linux? Does this library work on Linux?

**Comment by pfroud** [comment]
Hi,
I'm glad you appreciate this library :)
I have never tried it on Linux. But, I think it should work. If you tell me what Linux distribution you will use, I will test it.

**Comment by Jsing** [comment]
The Linux distribution has not been decided yet. We are in the exploration phase before product development.

We use Keysight's products. First, we need to check whether the visa library provided by Keysight supports Linux. If keysight does not support linux, we are forced to use Windows. 

Anyway, This library will be very useful to us. Thank you again : )

**Comment by pfroud** [comment]
This JVisa library is based on a project of the same name on Sourceforge by Günter Fuchs. Here is a line where it checks if the OS is Linux:
https://sourceforge.net/p/jvisa/code/HEAD/tree/trunk/JVisa/src/jvisa/JVisa.java#l148

For this JVisa library to work on Linux, we will need to do the same check so we can load a .so file instead of a .dll file.

**Comment by Jsing** [comment]
Thank you for kind explanation. Let me explain a little bit more about our situation.

Currently, We have our solution written by java which communicates some visa instruments. but we have a C# dll bridge between the visa driver and our solution. We are using JNI for it. Not everyone on our team likes this legacy structure. This has the following problems:

- We can't migrate our solution to Linux because of the C# dll bridge
- C# dll must be managed continuously and distributed separately.

We are looking for a library to use in Linux, but we may not actually apply it. I think just using JVisa on windows seems great. Maybe the decision will depend on the needs of the customer and the project situation.

Whatever direction the project goes, the values ​​you shared will be of great help to us.

**Comment by Jsing** [comment]
This is a different topic. Recently, I thought about contributing to an open source project. (Not sharing my code alone, but with someone else) I was first time, so I have been searched a very easy and small issue like `good first issue` in some repository. I think this issue is suitable for me as a beginner. May I try on this issue?

**Comment by pfroud** [comment]
Thanks for sharing some details your situation. I think JVisa on Windows would work well, and I think making JVisa work on Linux would not be very hard.

Sure, you're welcome to contribute to this project! I have never contributed to a real open source project either. I think this issue would be good for a beginner. Let me know if you have questions or want help.

**Comment by Jsing** [comment]
Yes. but I'm a little busy with some other proejct right now. this issue will be my joyful job when it's end-of-year holidays.

**Comment by pfroud** [comment]
I have learned that the JVisa code does NOT need to specify the file extension for the native library. JNA/Java will choose `.dll` for Windows, `.so` for Linux, or `.dylib` for macOS. See commit db499854ac5d6bb550e7d7d7f69f6c4c0971a149

**Comment by pfroud** [comment]
The newest release (JVisa-2022-03-02) will probably work on Linux: https://github.com/pfroud/JVisa/releases/tag/JVisa-2022-03-02

**Comment by Jsing** [comment]
I am so sorry. The fact that I couldn't get started bothered me. I had some personal free time, so I returned, and the problem has been resolved. Thank you so much for your sincere response.

**Comment by pfroud** [comment]
No problem, thanks for testing it.

What Linux distribution and version are you using? I'll update the Supported Platforms section in the Readme.

**Comment by pfroud** [comment]
I think I need to re-open the issue so you can reply...

**Comment by Jsing** [comment]
Oh sorry. When I first left a question here, we were in searching phase for development. Due to various circumstances, we decided to use window server and therefore we don't have linux environment. I just saw the code you fixed the problem with and said the problem was solved. I didn't test your code in linux. I am sorry again. You can close this issue.

**Comment by pfroud** [comment]
Understood, closing the issue now
